In [1]:
import numpy as np
from pulp import *

In [6]:
A=np.array([[3,1,2],[1,3,0],[0,2,4]])
b=np.array([60,36,48])
c=np.array([150,200,300])
print(A,b,c)

[[3 1 2]
 [1 3 0]
 [0 2 4]] [60 36 48] [150 200 300]


In [24]:
(m,n)=A.shape
print(m,n)

3 3


In [28]:
prob=LpProblem(name='production',sense=LpMaximize)
x=[LpVariable('x'+str(i+1),lowBound=0) for i in range(n)]
print(x)

[x1, x2, x3]


In [29]:
prob+=lpDot(c,x) # 这里使用lpDot 和 np.dot 结果都是一样地

In [30]:
for i in range(m):# 按行求点乘
    prob+=np.dot(A[i],x)<=b[i],'ineq'+str(i+1) # 这个地方如果前面重复跑了代码容易出现OVERLAPPING  的问题
print(prob)    

production:
MAXIMIZE
150*x1 + 200*x2 + 300*x3 + 0
SUBJECT TO
ineq1: 3 x1 + x2 + 2 x3 <= 60

ineq2: x1 + 3 x2 <= 36

ineq3: 2 x2 + 4 x3 <= 48

VARIABLES
x1 Continuous
x2 Continuous
x3 Continuous



In [31]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.


In [32]:
pip install xlrd

Note: you may need to restart the kernel to use updated packages.


In [51]:
import pandas as pd 
path=r'C:\Users\84280\Desktop\lianxi\olympic_data.xlsx'
print(path)
df=pd.read_excel(path,index_col=0)
df.head(10)

C:\Users\84280\Desktop\lianxi\olympic_data.xlsx


人口(100万人)  GDP(10億ドル)   金   銀   銅
アメリカ       321.774   14682.739  46  37  38
中国        1376.949    5320.232  26  18  26
イギリス        64.716    2676.520  27  23  17
ロシア        143.457     999.832  19  18  19
ドイツ         80.689    3236.726  17  10  15
フランス        64.395    2361.317  10  18  14
日本         126.573    4780.944  12   8  21
オーストラリア     23.969     975.012   8  11  10
イタリア        59.798    1745.045   8  12   8
カナダ         35.940    1359.773   4   3  15